guests =  []
guests.append("Ednaldo Pereira")
guests.append("Pedro Bial")
guests.append("Boneco do Posto")
guests.append("Coxinha")
print(guests.pop()+" Não vai conseguir participar da festa. Que pena!")
guests.append("Gil das Esfihas")
print(guests[-1]+" Tomará seu lugar!")
print("Convidando mais gente!")
guests.append("Anitta")
guests.insert(2,"Personalidade Brasileira 1")
guests.insert(5,"Personalidade Brasileira 2")
#print(guests)
guests.sort(reverse=True)
print(guests)
print("Temporary sorted list: "+str(sorted(guests)))
reversed_guests =  []
reversed_guests = guests.reverse()
print ("Virando ao contrario "+str(reversed_guests))
print ("\nO número de galeras lanchando é:",len(guests))
